services:
  app:
    # Execute nonsense command to ensure that the docker keeps running,
    # but does not start the pyramid servers as these are not needed for testing
    command: bash -c "tail -f /dev/null"
    volumes:
      - ${PWD}/htmlcov:/pyramid-app-caseinterview/htmlcov
      - ${PWD}/docs/_build:/pyramid-app-caseinterview/docs/_build
